#ifndef LIBQTREST_GLOBAL_H
#define LIBQTREST_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBQTREST_LIBRARY)
#  define LIBQTRESTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBQTRESTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBQTREST_GLOBAL_H
